; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@6.9.0	; TBA add to c3
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	; knolleary/PubSubClient@^2.8
	; khoih-prog/ESP_WifiManager@^1.12.1
	; https://github.com/me-no-dev/ESPAsyncWebServer.git
	; ayushsharma82/ESPConnect@^1.0.5
	; ayushsharma82/WebSerial@^1.3.0
	; adafruit/Adafruit NeoPixel@^1.12.0
	; ayushsharma82/AsyncElegantOTA@^2.2.8
	; wnatth3/WiFiManager@^2.0.16-rc.2
	; bblanchon/ArduinoJson@^7.0.4
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.0
	bblanchon/ArduinoJson@^7.0.4
	ayushsharma82/ElegantOTA@^3.1.5
	tzapu/WiFiManager@^2.0.17

board_build.partitions = min_spiffs.csv
build_flags = 
	; changed the next from 0 020825
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:esp32C3]
platform = espressif32 @ ^6.3.2
board = esp32-C3-DevKitM-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.0
	bblanchon/ArduinoJson@^7.0.4
	ayushsharma82/ElegantOTA@^3.1.5
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

board_build.partitions = min_spiffs.csv

board_build.arduino_usb_cdc = true
board_build.arduino_usb_mode = 1





[env:esp32c3supermini]
platform = espressif32
board = ESP32-C3-DevKitM-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions_2mb.csv

board_flash_size = 2MB
board_upload.flash_size = 2MB

board_build.arduino_usb_cdc = true
board_build.arduino_usb_mode = 1

build_flags =
    ; -DCONFIG_ESP_CONSOLE_USB_CDC=1
    ; -DARDUINO_USB_MODE=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	
lib_deps =
	; https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.0
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.0
	ayushsharma82/ElegantOTA@^3.1.5


[env:devkitM]
platform = espressif32
board = ESP32-C3-DevKitM-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.0
	bblanchon/ArduinoJson@^7.0.4
	ayushsharma82/ElegantOTA@^3.1.5
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

board_build.partitions = min_spiffs.csv

board_build.arduino_usb_cdc = true
board_build.arduino_usb_mode = 1

