; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32C3

[env]
monitor_filters = esp32_exception_decoder, direct
lib_ldf_mode = deep+
lib_deps =
  ayushsharma82/ElegantOTA @ ^3.1.5
  bblanchon/ArduinoJson @ ^7.0.4

build_flags = 
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -D VERSION_BUILD=${UNIX_TIME}
  -D CONFIG_ARDUHAL_LOG_COLORS=1  ; This forces the color codes in log output
  -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
  -D SERIAL_ON
  -I include ; so files in libs see the defines.h file at top level


[env:esp32dev]
platform = espressif32@6.9.0	; TBA add to c3
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
  ${env.build_flags}
lib_deps = 
  ${env.lib_deps}
	knolleary/PubSubClient@^2.8
	tzapu/WiFiManager@^2.0.17
board_build.partitions = min_spiffs.csv


[env:esp32C3]
platform = espressif32 @ ^6.3.2
board = esp32-C3-DevKitM-1
framework = arduino
monitor_speed = 115200
build_flags =
  ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
  ${env.lib_deps}
board_build.partitions = min_spiffs.csv
board_build.arduino_usb_cdc = true
board_build.arduino_usb_mode = 1