#pragma once

// Semantic version number
#define VERSION_MAJOR 0
#define VERSION_MINOR 38
#define VERSION_BUILD 92
#define VERSION_COMMENT "callbacks, throttle command"

// Build date/time (auto-generated by compiler)
#define VERSION_DATE __DATE__
#define VERSION_TIME __TIME__

// Combined string
#define VERSION_STRING \
  String(VERSION_MAJOR) + "." + \
  String(VERSION_MINOR) + "." + \
  String(VERSION_BUILD) + " (" + \
  VERSION_DATE + " " + VERSION_TIME + ")" + " " + \
  String(VERSION_COMMENT)
