#pragma once
#include "Arduino.h"

// Semantic version number
#define VERSION_MAJOR 0 
#define VERSION_MINOR 41
#define VERSION_COMMENT "Add ILocoStatus interface"

// Build date/time (auto-generated by compiler)
#define VERSION_DATE __DATE__ 
#define VERSION_TIME __TIME__

// Combined string
// const String VERSION_STRING = String(VERSION_MAJOR) + "." +
//                               String(VERSION_MINOR) + "." +
//                               String(VERSION_BUILD) + " " +
//                               VERSION_COMMENT;

// This string will look like: "0.40 (May 7 2024 14:30:05) Stable build"
// Use substring to grab only "HH:MM"
const String VERSION_STRING = String(VERSION_MAJOR) + "." + 
                             String(VERSION_MINOR) + 
                             " (" + VERSION_DATE + " " + String(VERSION_TIME).substring(0, 5) + ") " + 
                             VERSION_COMMENT;