#pragma once
#include "Arduino.h"

// Semantic version number
#define VERSION_MAJOR 0
#define VERSION_MINOR 39
// #define VERSION_BUILD 92 now comes from platformio.ini as unix time
#define VERSION_COMMENT "remove all mqtt, Serial calls, add doxygen, other cleanup"

// Build date/time (auto-generated by compiler)
#define VERSION_DATE __DATE__
#define VERSION_TIME __TIME__

// Combined string
const String VERSION_STRING = String(VERSION_MAJOR) + "." + 
                             String(VERSION_MINOR) + "." + 
                             String(VERSION_BUILD) + " (" + 
                             VERSION_DATE + " " + VERSION_TIME + ") " + 
                             VERSION_COMMENT;
